version: '3.8'

services:
  db:
    image: mysql:8.3
    ports:
      - 3307:3307
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: ru_cococo
      MYSQL_TCP_PORT: 3307
    volumes:
      - ./ru_cococo_db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - db_net

  web:
    build: ./ru_cococo_website
    ports:
      - "5000:5000"
    volumes:
      - ./ru_cococo_website:/app
    depends_on:
      - db
    networks:
      - db_net

volumes:
  db_data:

# Define the network.
networks:
  db_net: {}
